<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
//    public function findNextGames(){
//        $games = $this->getEntityManager()->createQuery(
//            'SELECT g FROM AppBundle:Game g WHERE g.data > CURRENT_TIMESTAMP() ORDER BY g.data ASC')
//            ->setMaxResults(12)
//            ->getResult();
//        return $games;
//    }
}
