<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRepository extends EntityRepository
{
    public function findMyType($user, $game){
        $type = $this->getEntityManager()->createQuery(
            'SELECT t FROM AppBundle:Type t WHERE t.user = :user AND t.game = :game')
            ->setParameter("user", $user)
            ->setParameter("game", $game)
            ->getOneOrNullResult();
        return $type;
    }

    public function findPreviousTypes($user){
        $types = $this->getEntityManager()->createQuery(
            'SELECT t FROM AppBundle:Type t JOIN t.game g WHERE (g.data < CURRENT_TIMESTAMP() AND t.user = :user) ORDER BY g.data ASC')
            ->setParameter('user', $user)
            ->setMaxResults(12)
            ->getResult();
        return $types;
    }

    public function findAllToTable(){
        $types = $this->getEntityManager()->createQuery(
            'SELECT t FROM AppBundle:Type t JOIN t.game g WHERE g.data < CURRENT_TIMESTAMP()')
            ->getResult();
        return $types;
    }





}
